# Generated by Django 4.0.6 on 2022-08-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_site', '0002_documentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmodel',
            name='document_type',
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='company_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
