# Generated by Django 4.0.6 on 2022-08-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_site', '0003_remove_documentmodel_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='document',
            field=models.CharField(max_length=100000),
        ),
    ]
