# Generated by Django 4.0.6 on 2022-08-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_site', '0006_rename_document_documentmodel_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='document_state',
            field=models.BooleanField(default=False),
        ),
    ]
