# Generated by Django 4.0.6 on 2022-08-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_site', '0008_alter_documentmodel_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='company_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='company_phone_number',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='company_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='content',
            field=models.TextField(),
        ),
    ]
